# Generated by Django 3.0.3 on 2020-07-03 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=50, verbose_name='firstName')),
                ('last_name', models.CharField(max_length=50, verbose_name='lastName')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('cnic', models.CharField(max_length=13, unique=True, verbose_name='cnic')),
                ('phone', models.CharField(max_length=11, verbose_name='phone')),
                ('address', models.CharField(max_length=150, verbose_name='address')),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(default='Pakistan', max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_client', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
